### ISSUE TITLE
启动报错 token __x64_blk_account_io_done: not found

### ISSUE THREAD

**Issue by surandor** [alibaba/kubeskoop#293]
failed start probe biolatency, err: link blk_account_io_done: creating perf_kprobe PMU (arch-specific fallback for "blk_account_io_done"): token __x64_blk_account_io_done: not found: no such file or directory

平台：Linux yang 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jzwlqx** [comment]
It means your kernel does not expose __x64_blk_account_io_done symbol. __x64_blk_account_io_done was removed in newer kernel.

However, we will remove biolatency probe in next release version of kubeksoop, a new latency diagnostic feature will be introduced, incorporating the capabilities that these probes used to offer.

**Comment by surandor** [comment]
There are two similar errors as follows：
failed start probe kernellatency, err: kernellatency failed load bpf: link kfree_skb: creating perf_kprobe PMU (arch-specific fallback for "kfree_skb"): token __x64_kfree_skb: not found: no such file or directory
failed start probe biolatency, err: link blk_account_io_start: creating perf_kprobe PMU (arch-specific fallback for "blk_account_io_start"): token __x64_blk_account_io_start: not found: no such file or directory

Is there any temporary solution to fix it?

**Comment by jzwlqx** [comment]
Try executing grep kfree_skb /proc/kallsyms to check if your kernel has exported the corresponding symbol. As far as I know, in newer kernel versions, kfree_skb is not exported, but __kfree_skb is still usable. I haven't looked closely to see if there is a replacement for blk_account_io_start. 

For a workaround, you can replace kfree_skb in the code with __kfree_skb, or avoid loading these two probes (since they will be deprecated later anyway).

**Comment by surandor** [comment]
Thanks, your advice helps a lot
